name: C/C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            cuda: "12.5.0"

    env:
      config: "Release"

    steps:
      - name: hardware info
        run: cat /proc/cpuinfo
      - name: Install native dependencies
        run: sudo apt-get install -y libhwloc-dev mpi-default-dev libhdf5-openmpi-dev

      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.17
        id: cuda-toolkit
        if: runner.os == 'Linux'
        with:
          sub-packages: '["nvcc", "nvrtc", "cudart"]'
          cuda: ${{ matrix.cuda }}
          method: network
          use-github-cache: false

      - name: nvcc check
        shell: bash
        run: |
          nvcc -V
          echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          ls "$CUDA_PATH"
          ls "$CUDA_PATH/bin"
          ls "$CUDA_PATH/include"

      - name: cmake version
        shell: bash
        run: cmake --version

      # make sure to explicitly checkout git submodule !
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: configure_openmp
        run: mkdir build_openmp && cd build_openmp && cmake -DPPKMHD_BUILD_KOKKOS=ON -DPPKMHD_BACKEND=OpenMP -DPPKMHD_USE_SDM=ON ..

      - name: make_openmp
        run: cd build_openmp && make

      - name: configure_cuda
        run: mkdir build_cuda && cd build_cuda && cmake -DPPKMHD_BUILD_KOKKOS=ON -DPPKMHD_BACKEND=Cuda -DKokkos_ARCH_AMPERE80=ON -DPPKMHD_USE_SDM=ON ..

      - name: make_cuda
        run: cd build_cuda && make
